# Generated by Django 3.1.4 on 2021-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20210207_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unparsed', max_length=255)),
                ('author_premium', models.BooleanField(default=False)),
                ('url', models.URLField(default='https://www.reddit.com/r/wallstreetbets')),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('downs', models.IntegerField()),
                ('ups', models.IntegerField()),
                ('name', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=155)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Unparsed', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(default='https://www.reddit.com/r/wallstreetbets'),
        ),
    ]
