# Generated by Django 3.1.4 on 2021-02-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20210211_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depth',
        ),
    ]
